title: TheDankDude172's Server
description: A thing
template:
  repo: thedankdude172's-server-template
  name: thedankdude172's-server
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
